# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/divide_and_count/divide_and_count.cache/wt [current_project]
set_property parent.project_path D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/divide_and_count/divide_and_count.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/divide_and_count/divide_and_count.srcs/sources_1/new/lab3_2.v
  D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/divide_and_count/divide_and_count.srcs/sources_1/new/lab3_1.v
  D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/divide_and_count/divide_and_count.srcs/sources_1/new/lab3_3.v
}
read_xdc D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/divide_and_count/divide_and_count.srcs/constrs_1/imports/lab03-Simple_sequential_circuit/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/divide_and_count/divide_and_count.srcs/constrs_1/imports/lab03-Simple_sequential_circuit/Nexys4DDR_Master.xdc]

synth_design -top divide_and_counter -part xc7a100tcsg324-1
write_checkpoint -noxdef divide_and_counter.dcp
catch { report_utilization -file divide_and_counter_utilization_synth.rpt -pb divide_and_counter_utilization_synth.pb }
