# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/xilinx_vivado/projects/lab2-Simple_combination_circuit/lab2_4/lab2_4.cache/wt [current_project]
set_property parent.project_path D:/xilinx_vivado/projects/lab2-Simple_combination_circuit/lab2_4/lab2_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/xilinx_vivado/projects/lab2-Simple_combination_circuit/lab2_4/lab2_4.srcs/sources_1/new/SELECT_MOUDLE.v
  D:/xilinx_vivado/projects/lab2-Simple_combination_circuit/lab2_4/lab2_4.srcs/sources_1/new/DECODER_MOUDLE.v
  D:/xilinx_vivado/projects/lab2-Simple_combination_circuit/lab2_4/lab2_4.srcs/sources_1/new/lab2_4.v
}
read_xdc D:/xilinx_vivado/projects/lab2-Simple_combination_circuit/lab2_4/lab2_4.srcs/constrs_1/imports/lab2_4/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/xilinx_vivado/projects/lab2-Simple_combination_circuit/lab2_4/lab2_4.srcs/constrs_1/imports/lab2_4/Nexys4DDR_Master.xdc]

synth_design -top Binary_to_BCD -part xc7a100tcsg324-1
write_checkpoint -noxdef Binary_to_BCD.dcp
catch { report_utilization -file Binary_to_BCD_utilization_synth.rpt -pb Binary_to_BCD_utilization_synth.pb }
