# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.cache/wt} [current_project]
set_property parent.project_path {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/sources_1/new/decoder3_8_plus.v}
  {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/sources_1/new/counter_plus.v}
  {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/sources_1/new/lab3_5_2.v}
  {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/sources_1/imports/new/lab3_1.v}
  {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/sources_1/new/lab3_4.v}
  {D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/sources_1/new/lab3_7.v}
}
read_xdc {{D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/constrs_1/imports/lab03-Simple_sequential_circuit/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/xilinx_vivado/projects/lab03-Simple_sequential_circuit/dynamic _scan/dynamic _scan.srcs/constrs_1/imports/lab03-Simple_sequential_circuit/Nexys4DDR_Master.xdc}}]

synth_design -top dynamic_scan_plus -part xc7a100tcsg324-1
write_checkpoint -noxdef dynamic_scan_plus.dcp
catch { report_utilization -file dynamic_scan_plus_utilization_synth.rpt -pb dynamic_scan_plus_utilization_synth.pb }
