# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.cache/wt [current_project]
set_property parent.project_path D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/sources_1/new/selector.v
  D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/sources_1/new/register.v
  D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/sources_1/new/memory.v
  D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/sources_1/new/full_adder.v
  D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/sources_1/new/comparator.v
  D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/sources_1/new/datapath_top.v
}
read_xdc D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/constrs_1/imports/lab04-Data_path_and_FSM/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/xilinx_vivado/projects/lab04-Data_path_and_FSM/data_path/data_path.srcs/constrs_1/imports/lab04-Data_path_and_FSM/Nexys4DDR_Master.xdc]

synth_design -top datapath -part xc7a100tcsg324-1
write_checkpoint -noxdef datapath.dcp
catch { report_utilization -file datapath_utilization_synth.rpt -pb datapath_utilization_synth.pb }
